### ISSUE TITLE
Colors not working when running from a PowerShell command prompt

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry-incubator/Diego-Enabler#1]
This is not a functional issue, just a FYI.
The text colors formatting isn't working correctly when run from within a Windows PowerShell command shell.

PS C:\> cf enable-diego jmptest01
Setting jmptest01 Diego support to true
[1;32mOk
[0m
Verifying jmptest01 Diego support is set to true
[1;32mOk
[0m
PS C:\>

![capture](https://cloud.githubusercontent.com/assets/1463614/12361801/05abaa3c-bb75-11e5-95cd-8995d6100e0c.JPG)

**Comment by dkoper** [comment]
Hi @jmprice 

Apologies for the late reply.
Colors should be working now, fixed in 1.1.0 of the plugin.

Regards,
Dies Koper
CF CLI PM
