### ISSUE TITLE
Missing the MAC OS binary download

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloudfoundry-incubator/Diego-Enabler#10]
I can no see a MAC OS binary.
Is the linux one which should be used?

Here is the to get binary files:
https://github.com/cloudfoundry-incubator/Diego-Enabler/releases/tag/v1.2.2

Downloads
9.89 MBdiego-enabler_darwin_amd64
8.65 MBdiego-enabler_linux_386
9.91 MBdiego-enabler_linux_amd64
8.64 MBdiego-enabler_windows_386.exe
9.86 MBdiego-enabler_windows_amd64.exe
Source code (zip)
Source code (tar.gz)

**Comment by dkoper** [comment]
It's the Darwin binary.

**Comment by dkoper** [comment]
If you follow these install instructions, it should download and install the applicable one for your platform.
```
$ cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org/
$ cf install-plugin Diego-Enabler -r CF-Community
```

**Comment by thomassuedbroecker** [comment]
Thanks, this installation works, but the MAC BIN should be there, because it is written in the readme.md or just change the readme.md.

// ---------------------
Möchten Sie das Plug-in Diego-Enabler installieren? (J oder N)> Y
Im Repository 'CF-Community' nach 'Diego-Enabler' suchen
10370188 Heruntergeladene Byte...
Installieren von Plug-in /var/folders/45/2dmjxyb97js_4s4rcx640kv80000gn/T/ filename=diego-enabler_darwin_amd64...
OK
Plug-in Diego-Enabler V1.2.2 wurde erfolgreich installiert. 
// ----------------------

**Comment by dkoper** [comment]
@thomassuedbroecker What readme.md are you referring to? What's written there that confused you?

**Comment by thomassuedbroecker** [comment]
I wanted to do this local and I followed this steps:

"First, copy the URL or download the binary for your platform from the latest release page.
Then call cf install-plugin with either the URL you copied or the binary you downloaded:"

**Comment by dkoper** [comment]
Gotcha! Thanks for the report.
