### ISSUE TITLE
cf migrate-apps ignores current target

### ISSUE THREAD

**Issue by rcruicks** [cloudfoundry-incubator/Diego-Enabler#11]
just ran migrate apps with current plug-in, expecting it to operate on current account/org/space target -- it rattled through *all* accessible orgs and spaces.

Surely not intended behaviour?

**Comment by dkoper** [comment]
That is the intended behaviour.
The original request for this command was to migrate *all* apps. We added `--org` and `--space` to restrict it to one org, or to a single space.

**Comment by rcruicks** [comment]
aha! thanks for clarifying, Dies - will look to highlight in local docs
