### ISSUE TITLE
not able to install the plugin

### ISSUE THREAD

**Issue by ajitrishabh** [cloudfoundry-incubator/Diego-Enabler#12]
not able to install the plugin

Searching CF-Community for plugin Diego-Enabler...
Plugin Diego-Enabler not found in repository CF-Community.
Use 'cf repo-plugins -r CF-Community' to list plugins available in the repo.
FAILED

**Comment by abbyachau** [comment]
Hi @ajitrishabh unfortunately this plugin is in the attic and it is no longer available to be downloaded.

**Comment by ajitrishabh** [comment]
@abbyachau  Okay. so how to i move my app to Diego? because i am not able to use **CF Sync Plugin**

**Comment by emalm** [comment]
Hey, @ajitrishabh, you can still install this plugin by downloading one of the binaries from the releases page (https://github.com/cloudfoundry-attic/Diego-Enabler/releases) to some location on your local workstation and then running `cf install-plugin $LOCAL_PATH_TO_PLUGIN`.

Best,
Eric, CF Diego PM
