### ISSUE TITLE
Getting error after installing the plugin-binary

### ISSUE THREAD

**Issue by evtimokn** [cloudfoundry-incubator/Diego-Enabler#2]
Hello,

I installed the precompiled version of Diego-enabler for windows. On cf enable-diego myapp I am getting:
Error: rpc: can't find method CliRpcCmd.GetApp
There is not much information on google about this, any idea what is missing? Thanks!

**Comment by evtimokn** [comment]
Updated cf to the last version 6.16 which fixed the problem

**Comment by dkoper** [comment]
Hi @evtimokn

What was your cf CLI version when you saw that error?

Cheers,
Dies Koper
CF CLI PM

**Comment by evtimokn** [comment]
Hi, It was 6.11.3, now I have 6.16.1

Best Regards,
Kalin

**Comment by dkoper** [comment]
Thanks. This plugin is for CLI v6.13.0+. For CLI v6.12.4 and older, you can use the Diego-Beta plugin instead but it doesn't have the new bulk migration commands.
I'll talk to the team what's involved in improving the error message for plugins with a minimum CLI requirement.

**Comment by evtimokn** [comment]
Thanks, should be ok as it is, some prerequisites are always there.
Am 08.04.2016 08:35 schrieb "Dies Koper" <notifications@github.com>:
