### ISSUE TITLE
golang rpc exception 

### ISSUE THREAD

**Issue by TomShacham** [cloudfoundry-incubator/Diego-Enabler#4]
```
tom$ cf enable-diego some-app
Setting some-app Diego support to true
2016/09/15 14:54:54 rpc: gob error encoding body: gob: type not registered for interface: []interface {}
FAILED
Error:  reading body EOF
```

While I can enable diego for every other app in my CF and Diego deployments, this *one* app gets this exception. 

Thanks!

**Comment by dkoper** [comment]
Hi @TomShacham 

Can you enable cf CLI trace and attach the output here if there is any?
Also, can you provide more details about your environment? Platform, cf CLI version, Diego-Enabler plugin version, CF release version (see output `cf api`), etc.

Cheers,
Dies Koper
CF CLI PM

**Comment by TomShacham** [comment]
Hi @dkoper thanks for your reply :)

Unfortunately the app was moved back to a DEA because it's quite critical. But the next time I see this bug I will re-run it with a CF_TRACE=true. 

> Also, can you provide more details about your environment? Platform, cf CLI version, Diego-Enabler plugin version, CF release version (see output cf api), etc.

Platform = vsphere
cf CLI version = 
> $ cf api
API endpoint: https://[redacted].com (API version: 2.59.0)

Diego-Enabler plugin version = 1.2.1
CF release version = 240 

Thanks!

**Comment by dkoper** [comment]
Hi @TomShacham 

We fixed a potentially related issue in the cf CLI (found as part of #3), which was incorporated in cf CLI version 6.21.1. I'll close this issue. Please submit a new one with CF trace if you see it again on the latest cf CLI?
