### ISSUE TITLE
Logging output errors with CF_TRACE=true cf enable diego

### ISSUE THREAD

**Issue by TomShacham** [cloudfoundry-incubator/Diego-Enabler#6]
## dependencies

may be similar to #3 

```
tom$ cf -v
cf version 6.22.1+6b7af9c-2016-09-24
```

Diego-Enabler v1.2.1

CF version 240
## issue

when running `CF_TRACE=true cf enable-diego <app>` you get the following error

```
FAILED
Error: unexpected end of JSON input
```

however, the command succeeds, because running `cf has-diego-enabled <app>` afterwards returns `true` and i have indeed checked that the app is running on a cell and not a dea. 

this is an issue because it means the command exits 1. 

just to be clear, running `cf enable-diego <app>` without `CF_TRACE=true` before it succeeds and exits 0. 

thanks!

**Comment by dkoper** [comment]
The team told me the issue indeed only occurs when CF_TRACE is enabled, and there is no easy way to fix this. Are you OK to keep using it without the trace enabled?

**Comment by TomShacham** [comment]
Yes we'll do our best :)

Do you know roughly when it might be fixed?

Thanks

**Comment by dkoper** [comment]
When we run out of other important things to do or when we start revamping the plugin architecture. Maybe in 3 months?

**Comment by TomShacham** [comment]
Okay thank you!

**Comment by dkoper** [comment]
I have added this to the [known issues list](https://github.com/cloudfoundry/cli/blob/master/README.md#known-issues), with tested work-arounds.
Closing this issue as we're not likely to get to addressing this in a reasonable timeframe.
Thanks again for reporting the issue.

Regards,
Dies Koper
CF CLI PM
