### ISSUE TITLE
Wrong version reported when install v1.2.2

### ISSUE THREAD

**Issue by JohnVandenbroek** [cloudfoundry-incubator/Diego-Enabler#9]
I installed the v1.2.2 plugins into cf cli v6.13.  This is what was written to sdtout:

Installing plugin diego-enabler_linux_amd64...
OK
Plugin Diego-Enabler **v1.2.1** successfully installed.

When listing cf plugins, this is written to stdout:

Listing Installed Plugins...
OK
 
Plugin Name     Version   Command Name                            Command Help
Diego-Enabler   **1.2.1**     enable-diego                            Migrate app to the Diego runtime
Diego-Enabler   **1.2.1**     disable-diego                           Migrate app to the DEA runtime
...

**Comment by mmb** [comment]
Thanks for reporting this issue. It is fixed now.

@mmb and @nickwei84
